In [19]:
import pandas as pd
from patsy import dmatrix
import numpy as np
import seaborn as sns

In [8]:
# 더미변수화
df2 = pd.DataFrame(['A', 'B', 'O', 'AB'], columns=['x'])
df2

x
0   A
1   B
2   O
3  AB

In [9]:
dmatrix('x+0', df2)

DesignMatrix with shape (4, 4)
  x[A]  x[AB]  x[B]  x[O]
     1      0     0     0
     0      0     1     0
     0      0     0     1
     0      1     0     0
  Terms:
    'x' (columns 0:4)

In [10]:
df3 = pd.DataFrame([1, 2, 3, 4], columns=['x'])
df3

x
0  1
1  2
2  3
3  4

In [11]:
dmatrix('x+0', df3)

DesignMatrix with shape (4, 1)
  x
  1
  2
  3
  4
  Terms:
    'x' (column 0)

In [13]:
dmatrix('C(x) + 0', df3) #카테고리 값으로 인식

DesignMatrix with shape (4, 4)
  C(x)[1]  C(x)[2]  C(x)[3]  C(x)[4]
        1        0        0        0
        0        1        0        0
        0        0        1        0
        0        0        0        1
  Terms:
    'C(x)' (columns 0:4)

In [18]:
dm = dmatrix("C(x, levels=['A', 'B', 'O', 'AB'])+0", df2)
np.array(dm)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
titanic = sns.load_dataset('titanic')
dmatrix('C(sex)', titanic)[:3]  #축소랭크

array([[1., 1.],
       [1., 0.],
       [1., 0.]])

In [23]:
dmatrix('sex+0', titanic)[:3]

array([[0., 1.],
       [1., 0.],
       [1., 0.]])

In [28]:
df4 = pd.DataFrame([["A", "X"],["B", "X"],["A", "Y"],["B", "Y"]], columns=['x1', 'x2'])
df4

x1 x2
0  A  X
1  B  X
2  A  Y
3  B  Y

In [29]:
dmatrix("x1+x2", df4)

DesignMatrix with shape (4, 3)
  Intercept  x1[T.B]  x2[T.Y]
          1        0        0
          1        1        0
          1        0        1
          1        1        1
  Terms:
    'Intercept' (column 0)
    'x1' (column 1)
    'x2' (column 2)

In [31]:
dmatrix("x1:x2 + 0", df4)

DesignMatrix with shape (4, 4)
  x1[A]:x2[X]  x1[B]:x2[X]  x1[A]:x2[Y]  x1[B]:x2[Y]
            1            0            0            0
            0            1            0            0
            0            0            1            0
            0            0            0            1
  Terms:
    'x1:x2' (columns 0:4)